version: '3.3'

services:

  ingress:
    image: nginx:stable-alpine
    volumes:
      - ./ingress/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    depends_on:
      - db-admin
    networks:
      - ingress-network

  db:
    image: mongo
    # restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      db-network:
        aliases:
          - mongo

  db-admin:
    image: mongo-express
    restart: always
    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - db
    networks:
      - db-network
      - ingress-network

networks:
  db-network:
  ingress-network:
